### ISSUE TITLE
Undefined variable

### ISSUE THREAD

**Issue by robin-j412** [jmather625/predicting-poverty-replication#3]
Hi, 

I'm working on your code but when I run download_image.py, It seems that df_mod_download (line 190) is not defined. 

I converted all ipynb files to python files using nbconvert, maybe it come from here.

I probably missed something, 

Let me know if you have this trouble, or if you want more information on my configuration.

Thanks

**Comment by jmathur25** [comment]
That is a hidden state problem, df_mod_download is defined shortly after. I just pushed a fix.
