### ISSUE TITLE
two small pieces of suggestions

### ISSUE THREAD

**Issue by luckystarufo** [jmather625/predicting-poverty-replication#4]
First of all, very great work!

I would like to suggest two points for those who may run your code in the future (as I spent a lot of time identifying these). 

1. In download_images.ipynb: please double check your Planet API token variable before using it, because on some machines the variable may have an extra '\n' when you load it from file and therefore creating 405 error when you access the data.
2. In train_cnn.ipynb: subprocess.call(["ln", "-s", src, dest]) may be used to replace os.system(f"ln -s {src} {dest}") as the latter cannot handle the cases where your path has white spaces;

**Comment by jmathur25** [comment]
Hi, thanks for the comments. To address them:

1) I can change `access = open(ACCESS_TOKEN_DIR, 'r').readlines()[0]` to `access = open(ACCESS_TOKEN_DIR, 'r').readlines()[0].strip()`, that would solve that problem.

2) valid, `os.system` is pretty coarse and if something goes wrong you only have the status code as an indication. I'll consider also changing that.
