### ISSUE TITLE
Zoom value for google api and pytorch version issue

### ISSUE THREAD

**Issue by EhsanAlahi** [jmather625/predicting-poverty-replication#6]
Hi, I was looking for an appropriate zoom value for google static map API. I found zoom value 14 in the planet downloader script. Should I use the same for google map API?
Thanks.

**Comment by jmathur25** [comment]
Use zoom = 16.

You can test out the download in the jupyter notebook on a given lat/lon/zoom as well to make sure the image seems of decent quality.

**Comment by EhsanAlahi** [comment]
These are two files I tested with two zoom (14 and 16) values. Which do you
think will be best for our task?
Thanks.

**Comment by jmathur25** [comment]
16 if using Google

**Comment by EhsanAlahi** [comment]
Thanks

**Comment by EhsanAlahi** [comment]
Hi Jatin, Sorry for bothering you again but I am facing some PyTorch
related issues. Actually I am using your pre-trained model weights but this
pre-trained model is not compatible with my current torch and torch-vision
versions. I would like to know the versions of torch and torch-vision with
which you trained that model. That will solve my compatibility issues,
otherwise, I would have to train a new model. Thanks in advance.

**Comment by jmathur25** [comment]
Hey Ehsan, here are the correct versions:

pytorch==1.3.0 torchvision==0.4.1

I've pushed a readme update and added a comment to help anyone else with these issues

**Comment by EhsanAlahi** [comment]
Thanks
